<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ExchangeRate;

class ExchangeRateSeeder extends Seeder
{
    public function run()
    {
        $currencies = [
            'AED' => ['symbol' => '&#1583;.&#1573;', 'name' => 'UAE Dirham'],
            'AFN' => ['symbol' => '&#65;&#102;', 'name' => 'Afghan Afghani'],
            'ALL' => ['symbol' => '&#76;&#101;&#107;', 'name' => 'Albanian Lek'],
            'ANG' => ['symbol' => '&#402;', 'name' => 'Netherlands Antillean Guilder'],
            'AOA' => ['symbol' => '&#75;&#122;', 'name' => 'Angolan Kwanza'],
            'ARS' => ['symbol' => '&#36;', 'name' => 'Argentine Peso'],
            'AUD' => ['symbol' => '&#36;', 'name' => 'Australian Dollar'],
            'AWG' => ['symbol' => '&#402;', 'name' => 'Aruban Florin'],
            'AZN' => ['symbol' => '&#1084;&#1072;&#1085;', 'name' => 'Azerbaijani Manat'],
            'BAM' => ['symbol' => '&#75;&#77;', 'name' => 'Bosnia-Herzegovina Mark'],
            'BBD' => ['symbol' => '&#36;', 'name' => 'Barbadian Dollar'],
            'BDT' => ['symbol' => '&#2547;', 'name' => 'Bangladeshi Taka'],
            'BGN' => ['symbol' => '&#1083;&#1074;', 'name' => 'Bulgarian Lev'],
            'BHD' => ['symbol' => '.&#1583;.&#1576;', 'name' => 'Bahraini Dinar'],
            'BIF' => ['symbol' => '&#70;&#66;&#117;', 'name' => 'Burundian Franc'],
            'BMD' => ['symbol' => '&#36;', 'name' => 'Bermudian Dollar'],
            'BND' => ['symbol' => '&#36;', 'name' => 'Brunei Dollar'],
            'BOB' => ['symbol' => '&#36;&#98;', 'name' => 'Bolivian Boliviano'],
            'BRL' => ['symbol' => '&#82;&#36;', 'name' => 'Brazilian Real'],
            'BSD' => ['symbol' => '&#36;', 'name' => 'Bahamian Dollar'],
            'BTN' => ['symbol' => '&#78;&#117;&#46;', 'name' => 'Bhutanese Ngultrum'],
            'BWP' => ['symbol' => '&#80;', 'name' => 'Botswanan Pula'],
            'BYR' => ['symbol' => '&#112;&#46;', 'name' => 'Belarusian Ruble'],
            'BZD' => ['symbol' => '&#66;&#90;&#36;', 'name' => 'Belize Dollar'],
            'CAD' => ['symbol' => '&#36;', 'name' => 'Canadian Dollar'],
            'CDF' => ['symbol' => '&#70;&#67;', 'name' => 'Congolese Franc'],
            'CHF' => ['symbol' => '&#67;&#72;&#70;', 'name' => 'Swiss Franc'],
            'CLP' => ['symbol' => '&#36;', 'name' => 'Chilean Peso'],
            'CNY' => ['symbol' => '&#165;', 'name' => 'Chinese Yuan'],
            'COP' => ['symbol' => '&#36;', 'name' => 'Colombian Peso'],
            'CRC' => ['symbol' => '&#8353;', 'name' => 'Costa Rican Colón'],
            'CUP' => ['symbol' => '&#8396;', 'name' => 'Cuban Peso'],
            'CVE' => ['symbol' => '&#36;', 'name' => 'Cape Verdean Escudo'],
            'CZK' => ['symbol' => '&#75;&#269;', 'name' => 'Czech Koruna'],
            'DJF' => ['symbol' => '&#70;&#100;&#106;', 'name' => 'Djiboutian Franc'],
            'DKK' => ['symbol' => '&#107;&#114;', 'name' => 'Danish Krone'],
            'DOP' => ['symbol' => '&#82;&#68;&#36;', 'name' => 'Dominican Peso'],
            'DZD' => ['symbol' => '&#1583;&#1580;', 'name' => 'Algerian Dinar'],
            'EGP' => ['symbol' => '&#163;', 'name' => 'Egyptian Pound'],
            'ETB' => ['symbol' => '&#66;&#114;', 'name' => 'Ethiopian Birr'],
            'EUR' => ['symbol' => '&#8364;', 'name' => 'Euro'],
            'FJD' => ['symbol' => '&#36;', 'name' => 'Fijian Dollar'],
            'FKP' => ['symbol' => '&#163;', 'name' => 'Falkland Islands Pound'],
            'GBP' => ['symbol' => '&#163;', 'name' => 'British Pound Sterling'],
            'GEL' => ['symbol' => '&#4314;', 'name' => 'Georgian Lari'],
            'GHS' => ['symbol' => '&#162;', 'name' => 'Ghanaian Cedi'],
            'GIP' => ['symbol' => '&#163;', 'name' => 'Gibraltar Pound'],
            'GMD' => ['symbol' => '&#68;', 'name' => 'Gambian Dalasi'],
            'GNF' => ['symbol' => '&#70;&#71;', 'name' => 'Guinean Franc'],
            'GTQ' => ['symbol' => '&#81;', 'name' => 'Guatemalan Quetzal'],
            'GYD' => ['symbol' => '&#36;', 'name' => 'Guyanaese Dollar'],
            'HKD' => ['symbol' => '&#36;', 'name' => 'Hong Kong Dollar'],
            'HNL' => ['symbol' => '&#76;', 'name' => 'Honduran Lempira'],
            'HRK' => ['symbol' => '&#107;&#110;', 'name' => 'Croatian Kuna'],
            'HTG' => ['symbol' => '&#71;', 'name' => 'Haitian Gourde'],
            'HUF' => ['symbol' => '&#70;&#116;', 'name' => 'Hungarian Forint'],
            'IDR' => ['symbol' => '&#82;&#112;', 'name' => 'Indonesian Rupiah'],
            'ILS' => ['symbol' => '&#8362;', 'name' => 'Israeli New Sheqel'],
            'INR' => ['symbol' => '&#8377;', 'name' => 'Indian Rupee'],
            'IQD' => ['symbol' => '&#1593;.&#1583;', 'name' => 'Iraqi Dinar'],
            'IRR' => ['symbol' => '&#65020;', 'name' => 'Iranian Rial'],
            'ISK' => ['symbol' => '&#107;&#114;', 'name' => 'Icelandic Króna'],
            'JEP' => ['symbol' => '&#163;', 'name' => 'Jersey Pound'],
            'JMD' => ['symbol' => '&#74;&#36;', 'name' => 'Jamaican Dollar'],
            'JOD' => ['symbol' => '&#74;&#68;', 'name' => 'Jordanian Dinar'],
            'JPY' => ['symbol' => '&#165;', 'name' => 'Japanese Yen'],
            'KES' => ['symbol' => '&#75;&#83;&#104;', 'name' => 'Kenyan Shilling'],
            'KGS' => ['symbol' => '&#1083;&#1074;', 'name' => 'Kyrgystani Som'],
            'KHR' => ['symbol' => '&#6107;', 'name' => 'Cambodian Riel'],
            'KMF' => ['symbol' => '&#67;&#70;', 'name' => 'Comorian Franc'],
            'KPW' => ['symbol' => '&#8361;', 'name' => 'North Korean Won'],
            'KRW' => ['symbol' => '&#8361;', 'name' => 'South Korean Won'],
            'KWD' => ['symbol' => '&#1583;.&#1603;', 'name' => 'Kuwaiti Dinar'],
            'KYD' => ['symbol' => '&#36;', 'name' => 'Cayman Islands Dollar'],
            'KZT' => ['symbol' => '&#1083;&#1074;', 'name' => 'Kazakhstani Tenge'],
            'LAK' => ['symbol' => '&#8365;', 'name' => 'Laotian Kip'],
            'LBP' => ['symbol' => '&#163;', 'name' => 'Lebanese Pound'],
            'LKR' => ['symbol' => '&#8360;', 'name' => 'Sri Lankan Rupee'],
            'LRD' => ['symbol' => '&#36;', 'name' => 'Liberian Dollar'],
            'LSL' => ['symbol' => '&#76;', 'name' => 'Lesotho Loti'],
            'LTL' => ['symbol' => '&#76;&#116;', 'name' => 'Lithuanian Litas'],
            'LVL' => ['symbol' => '&#76;&#115;', 'name' => 'Latvian Lats'],
            'LYD' => ['symbol' => '&#1604;.&#1583;', 'name' => 'Libyan Dinar'],
            'MAD' => ['symbol' => '&#1583;.&#1605;.', 'name' => 'Moroccan Dirham'],
            'MDL' => ['symbol' => '&#76;', 'name' => 'Moldovan Leu'],
            'MGA' => ['symbol' => '&#65;&#114;', 'name' => 'Malagasy Ariary'],
            'MKD' => ['symbol' => '&#1076;&#1077;&#1085;', 'name' => 'Macedonian Denar'],
            'MMK' => ['symbol' => '&#75;', 'name' => 'Myanma Kyat'],
            'MNT' => ['symbol' => '&#8366;', 'name' => 'Mongolian Tugrik'],
            'MOP' => ['symbol' => '&#77;&#79;&#80;&#36;', 'name' => 'Macanese Pataca'],
            'MRO' => ['symbol' => '&#85;&#77;', 'name' => 'Mauritanian Ouguiya'],
            'MUR' => ['symbol' => '&#8360;', 'name' => 'Mauritian Rupee'],
            'MVR' => ['symbol' => '.&#1923;', 'name' => 'Maldivian Rufiyaa'],
            'MWK' => ['symbol' => '&#77;&#75;', 'name' => 'Malawian Kwacha'],
            'MXN' => ['symbol' => '&#36;', 'name' => 'Mexican Peso'],
            'MYR' => ['symbol' => '&#82;&#77;', 'name' => 'Malaysian Ringgit'],
            'MZN' => ['symbol' => '&#77;&#84;', 'name' => 'Mozambican Metical'],
            'NAD' => ['symbol' => '&#36;', 'name' => 'Namibian Dollar'],
            'NGN' => ['symbol' => '&#8358;', 'name' => 'Nigerian Naira'],
            'NIO' => ['symbol' => '&#67;&#36;', 'name' => 'Nicaraguan Córdoba'],
            'NOK' => ['symbol' => '&#107;&#114;', 'name' => 'Norwegian Krone'],
            'NPR' => ['symbol' => '&#8360;', 'name' => 'Nepalese Rupee'],
            'NZD' => ['symbol' => '&#36;', 'name' => 'New Zealand Dollar'],
            'OMR' => ['symbol' => '&#65020;', 'name' => 'Omani Rial'],
            'PAB' => ['symbol' => '&#66;&#47;&#46;', 'name' => 'Panamanian Balboa'],
            'PEN' => ['symbol' => '&#83;&#47;&#46;', 'name' => 'Peruvian Sol'],
            'PGK' => ['symbol' => '&#75;', 'name' => 'Papua New Guinean Kina'],
            'PHP' => ['symbol' => '&#8369;', 'name' => 'Philippine Peso'],
            'PKR' => ['symbol' => '&#8360;', 'name' => 'Pakistani Rupee'],
            'PLN' => ['symbol' => '&#122;&#322;', 'name' => 'Polish Zloty'],
            'PYG' => ['symbol' => '&#71;&#115;', 'name' => 'Paraguayan Guarani'],
            'QAR' => ['symbol' => '&#65020;', 'name' => 'Qatari Rial'],
            'RON' => ['symbol' => '&#108;&#101;&#105;', 'name' => 'Romanian Leu'],
            'RSD' => ['symbol' => '&#1044;&#1080;&#1085;&#46;', 'name' => 'Serbian Dinar'],
            'RUB' => ['symbol' => '&#1088;&#1091;&#1073;', 'name' => 'Russian Ruble'],
            'RWF' => ['symbol' => '&#1585;.&#1587;', 'name' => 'Rwandan Franc'],
            'SAR' => ['symbol' => '&#65020;', 'name' => 'Saudi Riyal'],
            'SBD' => ['symbol' => '&#36;', 'name' => 'Solomon Islands Dollar'],
            'SCR' => ['symbol' => '&#8360;', 'name' => 'Seychellois Rupee'],
            'SDG' => ['symbol' => '&#163;', 'name' => 'Sudanese Pound'],
            'SEK' => ['symbol' => '&#107;&#114;', 'name' => 'Swedish Krona'],
            'SGD' => ['symbol' => '&#36;', 'name' => 'Singapore Dollar'],
            'SHP' => ['symbol' => '&#163;', 'name' => 'Saint Helena Pound'],
            'SLL' => ['symbol' => '&#76;&#101;', 'name' => 'Sierra Leonean Leone'],
            'SOS' => ['symbol' => '&#83;', 'name' => 'Somali Shilling'],
            'SRD' => ['symbol' => '&#36;', 'name' => 'Surinamese Dollar'],
            'STD' => ['symbol' => '&#68;&#98;', 'name' => 'São Tomé and Príncipe Dobra'],
            'SVC' => ['symbol' => '&#36;', 'name' => 'Salvadoran Colón'],
            'SYP' => ['symbol' => '&#163;', 'name' => 'Syrian Pound'],
            'SZL' => ['symbol' => '&#76;', 'name' => 'Swazi Lilangeni'],
            'THB' => ['symbol' => '&#3647;', 'name' => 'Thai Baht'],
            'TJS' => ['symbol' => '&#84;&#74;&#83;', 'name' => 'Tajikistani Somoni'],
            'TMT' => ['symbol' => '&#109;', 'name' => 'Turkmenistani Manat'],
            'TND' => ['symbol' => '&#1583;.&#1578;', 'name' => 'Tunisian Dinar'],
            'TOP' => ['symbol' => '&#84;&#36;', 'name' => "Tongan Pa'anga"],
            'TRY' => ['symbol' => '&#8356;', 'name' => 'Turkish Lira'],
            'TTD' => ['symbol' => '&#36;', 'name' => 'Trinidad and Tobago Dollar'],
            'TWD' => ['symbol' => '&#78;&#84;&#36;', 'name' => 'New Taiwan Dollar'],
            'UAH' => ['symbol' => '&#8372;', 'name' => 'Ukrainian Hryvnia'],
            'UGX' => ['symbol' => '&#85;&#83;&#104;', 'name' => 'Ugandan Shilling'],
            'USD' => ['symbol' => '&#36;', 'name' => 'US Dollar'],
            'UYU' => ['symbol' => '&#36;&#85;', 'name' => 'Uruguayan Peso'],
            'UZS' => ['symbol' => '&#1083;&#1074;', 'name' => 'Uzbekistan Som'],
            'VEF' => ['symbol' => '&#66;&#115;', 'name' => 'Venezuelan Bolívar'],
            'VND' => ['symbol' => '&#8363;', 'name' => 'Vietnamese Dong'],
            'VUV' => ['symbol' => '&#86;&#84;', 'name' => 'Vanuatu Vatu'],
            'WST' => ['symbol' => '&#87;&#83;&#36;', 'name' => 'Samoan Tala'],
            'XAF' => ['symbol' => '&#70;&#67;&#70;&#65;', 'name' => 'CFA Franc BEAC'],
            'XCD' => ['symbol' => '&#36;', 'name' => 'East Caribbean Dollar'],
            'XPF' => ['symbol' => '&#70;', 'name' => 'CFP Franc'],
            'YER' => ['symbol' => '&#65020;', 'name' => 'Yemeni Rial'],
            'ZAR' => ['symbol' => '&#82;', 'name' => 'South African Rand'],
            'ZMK' => ['symbol' => '&#90;&#75;', 'name' => 'Zambian Kwacha'],
            'ZWL' => ['symbol' => '&#90;&#36;', 'name' => 'Zimbabwean Dollar'],
        ];

        foreach ($currencies as $code => $data) {
            ExchangeRate::updateOrCreate(
                ['currency_code' => $code],
                [
                    'currency_symbol' => $data['symbol'],
                    'currency_name' => $data['name'],
                    'rate_to_usd' => 1.000000,
                    'is_active' => true,
                    'is_manual' => false,
                ]
            );
        }
    }
}
