<?php

namespace Database\Seeders;

use App\Models\TradingBot;
use Illuminate\Database\Seeder;

class TradingBotSeeder extends Seeder
{
    public function run()
    {
        $bots = [
            [
                'name' => 'ScalpX Pro',
                'description' => 'High-frequency scalping bot targeting crypto and forex micro-movements. Executes rapid trades with tight stop-losses for consistent small gains.',
                'strategy_type' => 'scalping',
                'win_rate' => 72,
                'expected_roi' => 2.5,
                'min_investment' => 100,
                'max_investment' => 5000,
                'profit_min_pct' => 0.5,
                'profit_max_pct' => 1.8,
                'loss_min_pct' => 0.3,
                'loss_max_pct' => 1.0,
                'trade_interval_minutes' => 5,
                'max_duration_days' => 30,
                'is_active' => true,
            ],
            [
                'name' => 'DayTrader Elite',
                'description' => 'Intraday momentum bot that identifies breakout patterns across all asset classes. Balances risk and reward with dynamic position sizing.',
                'strategy_type' => 'day_trading',
                'win_rate' => 65,
                'expected_roi' => 3.2,
                'min_investment' => 250,
                'max_investment' => 10000,
                'profit_min_pct' => 1.0,
                'profit_max_pct' => 3.5,
                'loss_min_pct' => 0.5,
                'loss_max_pct' => 2.0,
                'trade_interval_minutes' => 10,
                'max_duration_days' => 60,
                'is_active' => true,
            ],
            [
                'name' => 'SwingMaster',
                'description' => 'Multi-day swing trading bot focusing on stocks and ETFs. Captures medium-term trends using technical analysis and moving average crossovers.',
                'strategy_type' => 'swing',
                'win_rate' => 68,
                'expected_roi' => 4.0,
                'min_investment' => 500,
                'max_investment' => 25000,
                'profit_min_pct' => 2.0,
                'profit_max_pct' => 5.0,
                'loss_min_pct' => 1.0,
                'loss_max_pct' => 3.0,
                'trade_interval_minutes' => 15,
                'max_duration_days' => 90,
                'is_active' => true,
            ],
            [
                'name' => 'CryptoSniper',
                'description' => 'Aggressive crypto scalping bot that hunts for volatile altcoin moves. Higher risk, higher reward — designed for experienced traders.',
                'strategy_type' => 'scalping',
                'win_rate' => 60,
                'expected_roi' => 5.0,
                'min_investment' => 200,
                'max_investment' => 8000,
                'profit_min_pct' => 1.5,
                'profit_max_pct' => 4.0,
                'loss_min_pct' => 1.0,
                'loss_max_pct' => 2.5,
                'trade_interval_minutes' => 5,
                'max_duration_days' => 30,
                'is_active' => true,
            ],
            [
                'name' => 'Sentinel AI',
                'description' => 'AI-driven day trading bot that adapts to market conditions in real-time. Uses pattern recognition across crypto, forex, and indices.',
                'strategy_type' => 'day_trading',
                'win_rate' => 70,
                'expected_roi' => 3.8,
                'min_investment' => 500,
                'max_investment' => 15000,
                'profit_min_pct' => 1.2,
                'profit_max_pct' => 3.0,
                'loss_min_pct' => 0.4,
                'loss_max_pct' => 1.5,
                'trade_interval_minutes' => 8,
                'max_duration_days' => 45,
                'is_active' => true,
            ],
            [
                'name' => 'Apex Swing',
                'description' => 'Conservative swing bot for blue-chip stocks and major indices. Prioritizes capital preservation with steady, reliable returns over longer periods.',
                'strategy_type' => 'swing',
                'win_rate' => 75,
                'expected_roi' => 2.0,
                'min_investment' => 1000,
                'max_investment' => 50000,
                'profit_min_pct' => 1.0,
                'profit_max_pct' => 2.5,
                'loss_min_pct' => 0.3,
                'loss_max_pct' => 1.2,
                'trade_interval_minutes' => 20,
                'max_duration_days' => 90,
                'is_active' => true,
            ],
            [
                'name' => 'Turbo Scalp',
                'description' => 'Ultra-fast forex scalper targeting major currency pairs during peak volatility sessions. Small positions, high frequency, minimal drawdown.',
                'strategy_type' => 'scalping',
                'win_rate' => 78,
                'expected_roi' => 1.8,
                'min_investment' => 50,
                'max_investment' => 3000,
                'profit_min_pct' => 0.3,
                'profit_max_pct' => 1.2,
                'loss_min_pct' => 0.2,
                'loss_max_pct' => 0.8,
                'trade_interval_minutes' => 5,
                'max_duration_days' => 14,
                'is_active' => true,
            ],
            [
                'name' => 'Horizon Fund',
                'description' => 'Long-duration day trading bot combining momentum and mean-reversion strategies. Ideal for hands-off investors seeking diversified market exposure.',
                'strategy_type' => 'day_trading',
                'win_rate' => 66,
                'expected_roi' => 2.8,
                'min_investment' => 300,
                'max_investment' => 20000,
                'profit_min_pct' => 0.8,
                'profit_max_pct' => 2.8,
                'loss_min_pct' => 0.5,
                'loss_max_pct' => 1.8,
                'trade_interval_minutes' => 10,
                'max_duration_days' => 60,
                'is_active' => true,
            ],
        ];

        foreach ($bots as $bot) {
            TradingBot::create($bot);
        }
    }
}
